### ISSUE TITLE
Could popclip extension support icon picture?

### ISSUE THREAD

**Issue by leafonsword** [pilotmoon/PopClip-Extensions#1013]
I test a web search extension using color icon other than blank-white png, and new extension look and works well as below shows:
![default](https://user-images.githubusercontent.com/1754580/32439727-ef5ac37a-c32a-11e7-9534-6d5ba7ed19a8.png)
![default](https://user-images.githubusercontent.com/1754580/32439741-fe50d946-c32a-11e7-8a53-fd965720aa71.png)

So could popclip support icon picture?

**Comment by invariant** [comment]
Done - see Preserve Image Color key in extension config
