### ISSUE TITLE
Keyboard shortcut to trigger PopClip menu?

### ISSUE THREAD

**Issue by JmesPge** [pilotmoon/PopClip-Extensions#1017]
Can anybody tell me if there's a keyboard shortcut to trigger the PopClip menu in respective applications? Double-clicking on some websites and in some applications doesn't trigger displaying the menu, so it would be really useful to be able to trigger it manually.

If there isn't a keyboard shortcut, could it be added as a feature to future releases?

**Comment by invariant** [comment]
Take a look at http://docs.pilotmoon.com/article/36-controlling-popclip-using-applescript

**Comment by JmesPge** [comment]
Thanks - will check it out.
