### ISSUE TITLE
How to have multiple options on selected text

### ISSUE THREAD

**Issue by rootscript** [pilotmoon/PopClip-Extensions#1021]
Can you show an example of how to have an extension that has more than one button, like a dropdown.

When i look at how PopClip spelling works, it offers multiple suggestions, as separate buttons.

In my basic user case, I would like to be able to use the selected text to a choose 1 of 3 buttons from a dropdown.

Currently I can use the selected text with the List_01 extension, or another List_02 extension etc...

But I would like to be able to click on my button (like the arrow dropdown in attached image) to show the 3 options in one extension.

![menu_dropdown](https://user-images.githubusercontent.com/3963009/33499517-1658af9a-d6cd-11e7-8d6c-383755d90daf.jpg)

I would be grateful for some help

**Comment by invariant** [comment]
This isn't currently possible with extensions. (Spelling is a special case which is hard coded into the app.)
