### ISSUE TITLE
Agenda app

### ISSUE THREAD

**Issue by pilotmoon** [pilotmoon/PopClip-Extensions#1041]
Ref: **[Conversation #6394](https://secure.helpscout.net/conversation/517820832/6394) / Alif Aleph**

**Comment by jacobxk** [comment]
How is this issue going?

**Comment by invariant** [comment]
Ref: **[Conversation #6854](https://secure.helpscout.net/conversation/648491021/6854) / Mike**

**Comment by invariant** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Agenda](https://trello.com/c/yLBmS8oN/169-agenda)

**Comment by pilotmoon** [comment]
Done! https://www.popclip.app/extensions/x/62b6wp
