### ISSUE TITLE
Can't install extension

### ISSUE THREAD

**Issue by Canorus** [pilotmoon/PopClip-Extensions#1049]
error message saying "the applescript included cannot be open with Unicode text encoding" and I have no clue what I can do. Help needed.

![popclip_extension_errormessage](https://user-images.githubusercontent.com/7209435/38195518-c9328c30-36b8-11e8-8424-b4e0b47d7fea.png)

**Comment by invariant** [comment]
You must save your AppleScript as an .applescript text file.

.scpt file will not load.

**Comment by Canorus** [comment]
Oh so .applescript wasn't the deprecated name for applescript extension. I thought applescript changed its extension name from .applescript to .scpt something. Thanks for the help!

**Comment by invariant** [comment]
That's right, they are different file formats.
