### ISSUE TITLE
copy and paste issue

### ISSUE THREAD

**Issue by aderion** [pilotmoon/PopClip-Extensions#1073]
PopClip paste all the items in the clipboard instead of pasting the last item only !!, is this a known issue ? and if there is a fix or workaround

**Comment by aderion** [comment]
yes this Is a problem I am having with popclip

**Comment by invariant** [comment]
Hi, can you describe in more detail the problem? I'm not sure what you mean by "all the items in the clipboard"?

**Comment by icycles** [comment]
Not sure this is a PopClip-specific issue per se as wondering about potential conflicts with other clipboard managers, launchers, utilities, etc.

@aderion are you simultaneously using anything like Alfred, LaunchBar, BetterTouchTool, Copied, CopyClip, Paste, Pastebot, Quicksilver or the sort? Does the issue only occur when using PopClip extensions or also with keystrokes i.e. ⌘C, ⌘V, etc.?

Experienced similar issues as well wherein copied text would paste a series of (unintentionally) appended strings or something previously copied (i.e. not the _last_ thing) or clipboard contents failing to update entirely but disabling those features in competing/conflicting apps effectively ended the overlap. _'Too many cooks in the clipboard'_ it seems.

Might suggest doing the same and then test the behavior re-enabling settings one-by-one until you isolate the conflict(s), if that is indeed what's driving it. Did the same and results are 100% once again. Hopefully likewise, though if not and your preferred manager or utility is causing or contributing to the issue, maybe let that developer know as well as us here if you'd be so kind (as I'm admittedly also curious : ).

Here are some screenshots of those settings in Alfred and BTT: https://www.evernote.com/l/AARpr1cSy1hCRasWE0JSnwHgsFZfbSzCZKk
