### ISSUE TITLE
Fantastical extensions does not work with fantasticalcal2

### ISSUE THREAD

**Issue by bhishanpdl** [pilotmoon/PopClip-Extensions#1087]
I tried to use the popclip extension 'fantastical' to the latest version of fantastical calendar 'fantastical2' but it does not do anything.

Is there a new version of this extension?

**Comment by lordlycastle** [comment]
There're two extensions for FCal 3 and 2. Choose wisely!

**Comment by invariant** [comment]
Closing as per @lordlycastle comment (see https://pilotmoon.com/popclip/extensions/page/Fantastical2 and https://pilotmoon.com/popclip/extensions/page/Fantastical3)
