### ISSUE TITLE
How to display the result on the popclip bar

### ISSUE THREAD

**Issue by howardhhm** [pilotmoon/PopClip-Extensions#1104]
Some plugins need to display the result on the bar immediately, such as a timestamp.

**Comment by invariant** [comment]
For this you would use 

```xml
<key>After</key>
<string>show-result</string>
```

in the Action dictionary.

See for example the [Unix Time](https://github.com/pilotmoon/PopClip-Extensions/tree/master/source/UnixTime) extension.
