### ISSUE TITLE
Alfred v4 not supported

### ISSUE THREAD

**Issue by DasBlatz** [pilotmoon/PopClip-Extensions#1105]
Please add support for the new v4 of Alfred, old extension does not work anymore

**Comment by icycles** [comment]
As of Alfred 4, the bundle identifier for current and future versions has been unified to  'com.runningwithcrayons.Alfred' (versus previous version-specific IDs such as 'com.runningwithcrayons.Alfred-2' / '…-3' etc.).

If you feel like updating it yourself for immediate functionality, simply add the following entries to the extensions plist and php files, respectively:

**Config.plist**
+ `<string>com.runningwithcrayons.Alfred</string>`
→ to the `<key>Bundle Identifiers</key>` array
@ /Users/[username]/Library/Application Support/PopClip/Extensions/Alfred.popclipext/Config.plist

— and —

**alfred.php**
+ `$alfred3bid='com.runningwithcrayons.Alfred';`
→ `// select target app`
@ /Users/[username]/Library/Application Support/PopClip/Extensions/Alfred.popclipext/alfred.php

*Note: You'll need to nuke the _Signature.plist and change the 'pilotmoon' part of the Extension Identifier while you'll in there as these changes will break the code signing.
→ `<string>com.make-this-part-whatever.popclip.extension.append</string>`

Or, if you don't feel like doing all that…

→ [http://bit.ly/AlfredDasBlatz](http://bit.ly/AlfredDasBlatz)

: )

**Comment by invariant** [comment]
Done (d179511)
And published to https://pilotmoon.com/popclip/extensions/page/Alfred

Thanks @icycles
