### ISSUE TITLE
I can't add text for Todoist

### ISSUE THREAD

**Issue by giorgiobraz** [pilotmoon/PopClip-Extensions#1110]
**I can't add text to Todoist.**
Shows that I'm connected, but when I add it asks for new authentication.

**Comment by invariant** [comment]
This should now be fixed. Please donload latest extension from https://pilotmoon.com/popclip/extensions/page/Todoist.

Thanks for reporting.

**Comment by giorgiobraz** [comment]
Thank you very much. Please keep up the great work!! 😊

**Comment by pendolino** [comment]
i still seem to have this issue being asked to login repeatedly. i also seem to have this with the Instapaper plugin that used to work before.
