### ISSUE TITLE
How to change default text of 'Cut', 'Copy' of popup menu to icon?

### ISSUE THREAD

**Issue by dofine** [pilotmoon/PopClip-Extensions#1113]
![image](https://user-images.githubusercontent.com/440101/68007293-1b132e00-fcb6-11e9-9538-abdab3007423.png)
My system language is Chinese so the words of 'cut'(剪切) 'copy'(拷贝) really takes much screen space.
May I edit and change it to other icon/emoji?
Thanks!

**Comment by lordlycastle** [comment]
Email support. This is in app thing, not extensions. Unless you wish to create extensions that mimic that flow. (I would not recommend it as it'll be very difficult to get it perfect.)

**Comment by dofine** [comment]
For anyone who's interested, go to Mac OS system settings -> Languange, and change the languange setting of popclip to English(or whatever you like)

**Comment by invariant** [comment]
`defaults write com.pilotmoon.PopClip UseShortTitles -bool YES`

then restart PopClip, will set the labels to ⌘C, ⌘V and ⌘X instead of the localised language string.
