### ISSUE TITLE
[PopClip] [Todoist Extension] User gets logged out after adding the selected text to Todoist.

### ISSUE THREAD

**Issue by pwalen** [pilotmoon/PopClip-Extensions#1114]
Steps to Reproduce:
1. Click the PopClip icon on the menu bar.
2. Select the “Extensions” tab.
3. Click on the Pencil icon at the bottom of the tab.
4. Click on the Cog icon next to Todoist on the list.
5. Sign in to Todoist.
6. Select any text and select and click on Todoist icon on the PopClip menu.

Actual Result:
The “Sig into your Todoist account” popup is displayed underneath the PopClip icon on the menu bar.

Expected Result:
The user should be able to create a new task in Todoist.

Number of reproductions: 
10/10

Environment/Platform:
Device: Mac mini (2018)
Display: ASUS MX279/ 1920 x 1080 @ 60 Hz (1080p FHD)
App version / Build: PopClip 2019.9.1 / Todoist.popclipextz the latest version.
OS: macOS Catalina 10.15.1

Date/Time: 
18.10.2019, 8:04 (UTC)
![Screen Recording 2019-11-04 at 13 04 40](https://user-images.githubusercontent.com/41115724/68122947-e698af80-ff0b-11e9-9702-d924dfea2ef7.gif)

**Comment by Juul1** [comment]
Same issue here!

**Comment by invariant** [comment]
Thanks for reporting. Now fixed: https://pilotmoon.com/popclip/extensions/page/Todoist

**Comment by pwalen** [comment]
You are welcome :)
