### ISSUE TITLE
[PopClip][SnippetsLab] needs configuration update to support SetApp

### ISSUE THREAD

**Issue by rhm2k** [pilotmoon/PopClip-Extensions#1117]
Installed SnippetsLab within SetApp.
After install of PopClips extension for SnippetsLab, received:
> PopClip can’t find SnippetsLab on this computer. You probably need to install it.

**Comment by invariant** [comment]
Done, re-download from https://pilotmoon.com/popclip/extensions/page/SnippetsLab
