### ISSUE TITLE
Cannot Add: Malformed XML

### ISSUE THREAD

**Issue by mattyf** [pilotmoon/PopClip-Extensions#1118]
I'm having a similar issue to what the user was referencing in #783. I modified an existing popclip extension, but I get an error when I try to install it.

The path .../AmazonTrack.popclipext does not contain a valid PopClip extension.
Reason: Could not load Config.plist. The XML may be malformed. 

The suggested rebooting doesn't help, and I wasn't confusing .popclipext and .popclipextz

Any suggestions appreciated!!!

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Actions</key>
	<array>
		<dict>
			<key>AppleScript File</key>
			<string>AmazonTrack.applescript</string>
			<key>Image File</key>
			<string>omnitick.png</string>
			<key>Title</key>
			<string>AmazonTrack</string>
		</dict>
	</array>
	<key>Apps</key>
	<array>
		<dict>
			<key>Link</key>
			<string>http://www.omnigroup.com/products/omnifocus/</string>
			<key>Name</key>
			<string>OmniFocus</string>
		</dict>
	</array>
	<key>Credits</key>
	<array>
		<dict>
			<key>Name</key>
			<string>Marc Abramowitz</string>
		</dict>
	</array>
	<key>Extension Description</key>
	<string>Create a new task in OmniFocus. (Supports OmniFocus 1 and OmniFocus 2 Pro.)</string>
	<key>Extension Identifier</key>
	<string>com.pilotmoon.popclip.extension.amazontrack</string>
	<key>Extension Name</key>
	<string>AmazonTrack</string>
	<key>Required Software Version</key>
	<integer>693</integer>
</dict>
</plist>
```

**Comment by apaperumbrella** [comment]
Hi, I am confronted with the some problem, has it been solved?

**Comment by mattyf** [comment]
I ended up getting this to work by stripping out every line that wasn't specifically needed.

Then make sure to remove "pilotmoon" from the identifier. See if that works.

**Comment by invariant** [comment]
Closing old issue. If you are still having any trouble you can always email me support@pilotmoon.com
