### ISSUE TITLE
cannot install the custom extension

### ISSUE THREAD

**Issue by apaperumbrella** [pilotmoon/PopClip-Extensions#1119]
After creating my own custom extension for PopClip following the procedures of Jordan Merrick(https://computers.tutsplus.com/tutorials/create-your-own-custom-extension-for-popclip--mac-50637),  I am confronted with a problems as shown in the Figure (...does not contain a valid PopClip extension. Reason: Could not load Config.plist. The XML may be malformed.).  Has any one known how to solve it. Thanks!
<img width="420" alt="屏幕快照 2020-01-10 下午10 27 23" src="https://user-images.githubusercontent.com/20382100/72160091-b6ccc300-33f8-11ea-9b84-2e1130ba243e.png">

**Comment by invariant** [comment]
It means the XML file has a syntax error. Closing this issue as it is really a support request. I you still have the trouble you can email me support@pilotmoon.com.
