### ISSUE TITLE
Loop in login Todoist extension

### ISSUE THREAD

**Issue by LETRA** [pilotmoon/PopClip-Extensions#1120]
Hi. This extension looks like it's in trouble again. When I try to use it, I  get a loop asking for login authorization.

![Captura de pantalla 2020-01-24 a las 1 56 53](https://user-images.githubusercontent.com/16805254/73036758-de864700-3e4c-11ea-87ce-50cf96da6b2c.jpg)

-----------------

![Captura de pantalla 2020-01-24 a las 1 57 03](https://user-images.githubusercontent.com/16805254/73036753-da5a2980-3e4c-11ea-90e2-c4eea695b157.jpg)

**Comment by Juul1** [comment]
Same here

**Comment by invariant** [comment]
Now fixed (again): https://pilotmoon.com/popclip/extensions/page/Todoist

**Comment by LETRA** [comment]
Works good. Thank you :)
