### ISSUE TITLE
Reminders.popclipextz doesn't work

### ISSUE THREAD

**Issue by YELLOWHOMEIN** [pilotmoon/PopClip-Extensions#1121]
the reminder app can be evoke, but it can't not add a new reminders.  How to fix it？

**Comment by stevenrasz** [comment]
I had trouble with this one too. Instead, I created a shell script extension with the following code to run AppleScript from there.

`osascript -e \
'on run {myinput}
	tell application "Reminders"
		activate
		set myReminder to (make new reminder with properties {name:myinput})
		show myReminder
	end tell
end run' "$POPCLIP_TEXT"`

**Comment by invariant** [comment]
Closing this one - kind of dupe of #793 
The old Reminders extension stopped working. I need to do a new one.
Thanks for code snippet, @audero-cmyk
