### ISSUE TITLE
Fantastical 3 update breaks Popclip extension

### ISSUE THREAD

**Issue by ericwass** [pilotmoon/PopClip-Extensions#1122]
self-explanatory... Popclip is throwing an error. Anybody know how to fix? Thanks

**Comment by phersh** [comment]
Nothing happens when I highlight text and choose the Fantastical extension. I uninstalled and re-installed it but I go the same behavior.

**Comment by invariant** [comment]
This is fixed in the latest Fantastical extension: https://pilotmoon.com/popclip/extensions/page/Fantastical3
