### ISSUE TITLE
Bitly v3 API Deprecated - Bitly Support Will Stop Working March 1 2020

### ISSUE THREAD

**Issue by aaronk1** [pilotmoon/PopClip-Extensions#1123]
@invariant Please update the Bitly extension to use the new v4 API before March 1 2020 or the extension will stop working.  Note it uses OAuth access tokens instead of API keys.

More details:
https://support.bitly.com/hc/en-us/articles/360004395631

**Comment by fishcymbal** [comment]
Is this likely to get updated or are there too few PopClip users who also use Bitly?

**Comment by invariant** [comment]
It's on my todo list, it ust might take me a while to get to it.

**Comment by selsrog** [comment]
Just found out about this PopClip Bitly extension...
So a +1 from me to have this updated ;-).
Thanks in advance!

**Comment by invariant** [comment]
Now updated. Redownload from https://pilotmoon.com/popclip/extensions/page/Bitly
Thanks all.
