### ISSUE TITLE
How to config shortcut  for my extend plugin?

### ISSUE THREAD

**Issue by lhsaq2009** [pilotmoon/PopClip-Extensions#1124]
There is a  translate app on my mac.
The app support custome shortcut to translate text of selected.

like `command + 1`

So，I want to create a extension for trigger `command + 1`

I  encounter a problem with how to config shortcut.  

Any help would be greatly appreciated!

**Comment by invariant** [comment]
I'm closing this as it's a question not an issue; but you are welcome to email me at support@pilotmoon.com if you still have the problem.
