### ISSUE TITLE
Wrong unicode is used for special characters with UPPERCASE/lowercase plugins

### ISSUE THREAD

**Issue by mesqueeb** [pilotmoon/PopClip-Extensions#1126]
I write this with my keyboard:
```
À
```
then I write this, and I convert it uppercase of PopClip:
```
à
```
it becomes
```
À
```

now I copy past both and log the charCode in JS:
```js
'À'.charCodeAt(0) // 192
'À'.charCodeAt(0) // 65
```

Github comments seem to normalise this so I can't properly paste the difference...

but the top one is written with my keyboard, and the bottom one with popclip's uppercase conversion:

<img width="134" alt="image" src="https://user-images.githubusercontent.com/3253920/79031663-38d8ad80-7bdb-11ea-981b-644da3eabf1c.png">

**Comment by mesqueeb** [comment]
followup:
you can see in VSCode it's not recognised to be the same string any more...
 
![2020-04-11 10 05 21](https://user-images.githubusercontent.com/3253920/79031754-0f6c5180-7bdc-11ea-956c-6aa121ed9ecf.gif)

**Comment by mesqueeb** [comment]
Ok it's about this:

- "NFC"
Canonical Decomposition, followed by Canonical Composition.
- "NFD"
Canonical Decomposition.

there is no right or wrong answer...

**Comment by mesqueeb** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

**Comment by invariant** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Uppercase etc fails with unicode chars](https://trello.com/c/98r4Zrz5/132-uppercase-etc-fails-with-unicode-chars)

**Comment by mesqueeb** [comment]
@invariant FYI, I think it makes most sense that you keep the original status of special characters:

- ①　special characters that are using "canonical decomposition" (under the hood 2 characters)
  - should be made capital / lower case by using the "canonical decomposition" version of its capital / lower case version.
- ②　special characters that are using "canonical composition" (under the hood 1 character)
  - should be made capital / lower case by using the "canonical composition" version of its capital / lower case version.

**Comment by pilotmoon** [comment]
Just going through some issues. I wonder, did this get resolved with the shift to JavaScript?

**Comment by mesqueeb** [comment]
@pilotmoon I just double checked and it seems to be fixed! :tada: 

NFD keeps NFD no matter how many times we convert,
and same for NFC
