### ISSUE TITLE
Extension Request: convert hex color to name

### ISSUE THREAD

**Issue by mesqueeb** [pilotmoon/PopClip-Extensions#1127]
There's a tool I always use that converts hex/rgba colors to a unique color name:
http://chir.ag/projects/name-that-color/#6195ED

I'd love to have an extension in popclip that can take a hex or rgba string and replace it with the color name! 🎨

**Comment by oxxie** [comment]
Hi @mesqueeb , see #1135 for a suggestion on my end! :-)

**Comment by invariant** [comment]
Done thanks to @oxxie. Quick download link: https://github.com/pilotmoon/PopClip-Extensions/blob/master/extensions/NameColor.popclipextz?raw=true

**Comment by mesqueeb** [comment]
@oxxie @invariant it doesn't seem to come with an icon. Is it possible to have it use an icon like other extensions?
<img width="156" alt="image" src="https://user-images.githubusercontent.com/3253920/98610147-549f6000-2332-11eb-97b7-5bac2b1e4a21.png">

The functionality is great though!

**Comment by oxxie** [comment]
@mesqueeb This is certainly possible! Do you have any suggestions of what this icon should look like? Some example pictures would be nice.

**Comment by mesqueeb** [comment]
Maybe some kind of color picker? Like this one:
```html
<svg xmlns="http://www.w3.org/2000/svg" style="color:rgb(171,146,240);" width="20" height="20" viewBox="0 0 20 20"><g fill="none" fill-rule="evenodd"><path fill="currentColor" d="M7.536 15.236c-1.56.617-4.257 2.371-4.728 1.9-.306-.305.323-1.546.972-2.805h4.66l-.905.905z"/><path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16.51 6.262l-8.974 8.974c-1.56.617-4.257 2.371-4.728 1.9-.472-.471 1.283-3.169 1.9-4.728l8.974-8.975m0 0h0a2 2 0 0 1 2.828 0h0a2 2 0 0 1 0 2.829h0m-6.366-2.124l5.657 5.657"/></g></svg>
```

**Comment by oxxie** [comment]
Nice suggestion! See #1141 :-)
