### ISSUE TITLE
Selecting text in iTerm2 doesn't activate PopClip

### ISSUE THREAD

**Issue by angelus2014** [pilotmoon/PopClip-Extensions#1129]
When selecting text in iTerm2, PopClip doesn't get activated so in effect it's not working inside iTerm2.

**Comment by gatspy** [comment]
hope, sloved this isssue as soon.

**Comment by invariant** [comment]
Are you still having this problem? Is so can you tell me the exact iTerm2 version number. Thanks.

**Comment by angelus2014** [comment]
Hello,

> Are you still having this problem? Is so can you tell me the exact iTerm2 version number. Thanks.

At the moment I’m not using PopClip anymore, but the last time, it worked, but intermittent. So sometimes the menu would show up and sometimes not. There didn’t seem to be any consistent factor regarding whether PopClip would work. My version is the latest, stable one: Build 3.3.12.


---
With regards,

Angelo Machils

**Comment by invariant** [comment]
Thanks @angelus2014. How about you @gatspy?

**Comment by invariant** [comment]
I'm closing this now. I added a new cursor definition for compatibility with a certain version iTerm2. If any further trouble with iTerm2, please report it to me by email support@pilotmoon.com and I will investigate.
