### ISSUE TITLE
Open in firefox doesn't appear in the popclip popup

### ISSUE THREAD

**Issue by jbaruch** [pilotmoon/PopClip-Extensions#1130]
After adding and enabling the extension it doesn't appear in the popup:
<img width="916" alt="config" src="https://user-images.githubusercontent.com/247332/86521583-ba6d5f80-be07-11ea-804a-53c25b4c4d26.png">
<img width="916" alt="popup" src="https://user-images.githubusercontent.com/247332/86521630-24860480-be08-11ea-9b78-d556464b8f30.png">

**Comment by invariant** [comment]
It will appear if you select a URL anywhere outside of Firefox.
