### ISSUE TITLE
Convert extension error Use of undefined constant 

### ISSUE THREAD

**Issue by bradleysawler** [pilotmoon/PopClip-Extensions#1134]
When I try to convert 140°F or 140.0F or 140,0F I get the following error. I note that it converts it correct a the end to 60.0°C. I set PopClip English setting to English (US) an Englis (Australia) with the same affect. 

version: 2019.10 (1003032) on macOS 10.15.7 (19H2).

Warning: Use of undefined constant ALL_SEPARATORS - assumed 'ALL_SEPARATORS' (this will throw an Error in a future version of PHP) in /Users/bgs/Library/Application Support/PopClip/Extensions/Convert.popclipext/convert.php on line 3

Warning: Use of undefined constant DECIMAL_SEPARATOR - assumed 'DECIMAL_SEPARATOR' (this will throw an Error in a future version of PHP) in /Users/bgs/Library/Application Support/PopClip/Extensions/Convert.popclipext/convert.php on line 6
60.0°C

The same with 200 pounds: 

Warning: Use of undefined constant ALL_SEPARATORS - assumed 'ALL_SEPARATORS' (this will throw an Error in a future version of PHP) in /Users/bgs/Library/Application Support/PopClip/Extensions/Convert.popclipext/convert.php on line 3

Warning: Use of undefined constant DECIMAL_SEPARATOR - assumed 'DECIMAL_SEPARATOR' (this will throw an Error in a future version of PHP) in /Users/bgs/Library/Application Support/PopClip/Extensions/Convert.popclipext/convert.php on line 6
90.7 kg

**Comment by invariant** [comment]
Thanks for the report - now fixed (247cf73). You'll need to redownload from https://pilotmoon.com/popclip/extensions/page/Convert.
