### ISSUE TITLE
Instant Translate - popClip

### ISSUE THREAD

**Issue by nuhlis** [pilotmoon/PopClip-Extensions#1146]
Hello guys,

I love popClip and a lot of times I'm using Instant Translate. Put after updating to Big Sur, it's stopped working. I'm trying to translate and  it show "X". Extension is downloaded throught popClip extension site, so it should be updated. Some help, please?

**Comment by invariant** [comment]
Thanks - seems like something wrong with the extension or the Microsoft server changed the API or some such. Will investigate.

**Comment by invariant** [comment]
Oh jeez. Why did I write this in python? I don't even remember how to print a debug string in python...

**Comment by nuhlis** [comment]
Just notice, that you deleted the Instant Translate from extensions website. Is it lost?

**Comment by invariant** [comment]
It stopped working, something to do with an API change or perhaps SSL certificate on the Azure stuff. I've removed it from the website until it is fixed, since there is no point listing an extension that doesn't work :)

**Comment by invariant** [comment]
So, it seems this started working again. Whatever the problem was with the server or the API, it has gone away. So I have put it back on the website. Closing for now.

**Comment by nuhlis** [comment]
I just used it just yesterday and I was glad that it worked. Thanks Nick, great job!


Sent from MacBook. 

Yours sincerely and with the wish of a nice day Tomas Nuhlicek.

+1 (720) 691-9678
tom.nuhlicek@seznam.cz

**Comment by elighter** [comment]
Hi @invariant 

The same problem persists after 11.2.3 update.

**Comment by invariant** [comment]
Thanks for reporting. It seems to be due to an error reporting a SSL certificate expiry. It's going to take some exploration to fix it.

If anyone reading this is able to fix the extension, please go ahead. I

**Comment by harrtho** [comment]
I have an updated working version. But due to the changes in macOS 12.3 where Apple removed python, the extension now depends on the python3 path of home brew` /usr/local/bin/python3`. If this doesn't matter I'm happy to create a pull request :)

**Comment by harrtho** [comment]
In the mean time I pushed to my fork and published a "release" https://github.com/harrtho/PopClip-Extensions

**Comment by invariant** [comment]
Thank you. One thing you can do is change the hardcoded path to just python3. That way it will look up the python3 executable whever it is in the user's PATH variable.

**Comment by invariant** [comment]
Updated and released: https://pilotmoon.com/popclip/extensions/page/InstantTranslate
