### ISSUE TITLE
need a extension : open in vivaldi

### ISSUE THREAD

**Issue by LeokuJessica** [pilotmoon/PopClip-Extensions#1152]
I don't know how to use url-schemes but I do want to use popclip as a quicker entrance to vivaladi

**Comment by lordlycastle** [comment]
Options: 
 1. Set Vivaldi as you default browser.
 2. A simple shell script command `open -a Vivaldi.app $url`.
 3. A more complex login with AppleScript e.g. grabbing foremost window etc. (This will be hard if you're new)

[Read the instructions on how to make extensions](https://github.com/pilotmoon/PopClip-Extensions)

**Comment by invariant** [comment]
Done in 79542b9, see: https://pilotmoon.com/popclip/extensions/page/OpenInVivaldi
