### ISSUE TITLE
Baidu search extension will automatically copy every time while Google search extension will not

### ISSUE THREAD

**Issue by tortoo** [pilotmoon/PopClip-Extensions#1153]
This happened on  M1 Mac mini. I think  it's a new bug and please fix it.

**Comment by invariant** [comment]
Thanks for reportting . This is the same issue as #1148

**Comment by invariant** [comment]
My mistake, it's actually different (Search action vs extensions). Reopening.

**Comment by invariant** [comment]
Fixed in 2019.9
