### ISSUE TITLE
Some extensions like “underscore” and “hyphenate” don’t work under macOS 12

### ISSUE THREAD

**Issue by realliyifei** [pilotmoon/PopClip-Extensions#1159]

**Comment by invariant** [comment]
Thank you. Yes this is because macOS 12 doesn't ship with PHP. Still figuring out the best solution but whatever it I hope to have it in time for the release of Monterey.

**Comment by shawnhank** [comment]
I think I'm having the same issue with PopClip after trying to install the Todoist extension.

Here's a [screenshot of the error message I keep seeing.](https://p140.p3.n0.cdn.getcloudapp.com/items/JruxkKRx/02be1e8c-ab27-4e07-91f8-0447c52d0b25.png?v=147ccbef17ceb67ff304bb65661673c5). 

I've installed PHP 7.4 using brew, added it to my path in both bash and zsh, but it still isn't working. Any suggestions?

Thanks!

**Comment by invariant** [comment]
You would also need to modify the extension's Config.plist to set the Script Interpreter field to point to wherever the homebrew php installation is (as reported by `which php`).

**Comment by invariant** [comment]
Now addressed. See: https://pilotmoon.com/blog/2021/09/15/popclip-macos-monterey
