### ISSUE TITLE
eudic extension bug

### ISSUE THREAD

**Issue by cks2015** [pilotmoon/PopClip-Extensions#1164]
macos : 11.6
popclip:  2021.9 (1003510)

popclip update from app store   ( 2021.4  to  2021.9)

eudic extension prompt error  ( Bundle Identifler must be a string)

<img width="254" alt="eduic_error" src="https://user-images.githubusercontent.com/11919837/134611757-c1117061-5729-4dcd-98f7-0cc8aa0c4b49.png">

**Comment by invariant** [comment]
Fixed in bac85dfc64bd7ada4a70b236f6955e636f121801, thanks for rerorting.

**Comment by cks2015** [comment]
> Fixed in [bac85df](https://github.com/pilotmoon/PopClip-Extensions/commit/bac85dfc64bd7ada4a70b236f6955e636f121801), thanks for reporting.

thanks  fix this bug
