### ISSUE TITLE
URLEncode extension: Required Apps key in Config.plist (should be Required Software Version)

### ISSUE THREAD

**Issue by RalphBln** [pilotmoon/PopClip-Extensions#1165]
Config.plist of the URLEncode extension contains the following two lines:

```
<key>Required Apps</key>
<integer>701</integer>
```

As a result the extension can no longer be installed.

Should be:

```
<key>Required Software Version</key>
<integer>701</integer>
```

**Comment by invariant** [comment]
Many thanks. Working on an update (and [rewrite in Javascript for Monterey](https://pilotmoon.com/blog/2021/09/15/popclip-macos-monterey)) now.
