### ISSUE TITLE
Email doesn't appear to distinguish email addresses?

### ISSUE THREAD

**Issue by charlesweir** [pilotmoon/PopClip-Extensions#1172]
When I select an email address (e.g. a@a.com) and PopClip the 'Email' plug-in, it puts the address as a link in the body (Microsoft Outlook), not in the To field.

Yet mailto:a@a.com in the (Chrome or Safari) browser address field correctly brings up the address in the Outlook To field. 

How do I make PopClip email put the email address in the To field?

- Charles

**Comment by charlesweir** [comment]
Hi Nick,

I don’t see the @ icon anywhere (even when I select ***@***.***’). How do I enable it?

Best regards,

Charles

From: Nick Moore ***@***.***>
Reply to: pilotmoon/PopClip-Extensions ***@***.***>
Date: Thursday, 9 December 2021 at 15:50
To: pilotmoon/PopClip-Extensions ***@***.***>
Cc: "Weir, Charles" ***@***.***>, Author ***@***.***>
Subject: Re: [pilotmoon/PopClip-Extensions] Email doesn't appear to distinguish email addresses? (Issue #1172)


This email originated outside the University. Check before clicking links or attachments.

The Email extension has two actions, one for creating a new email with selected text as body (envelope icon) and one for composing a new email to the selected address (@ icon) -- can you confirm you are using the latter?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpilotmoon%2FPopClip-Extensions%2Fissues%2F1172%23issuecomment-989976828&data=04%7C01%7Cweirc1%40live.lancs.ac.uk%7C846d1650df2c4428f41f08d9bb2b9022%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637746618037515268%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mW5l8GrTPjNqi%2B6nkxWSwUmnQynEfyXxcpjLzdmXE4c%3D&reserved=0>, or unsubscribe<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAAGCZT5KEQQ44AKAXVHTQO3UQDF2PANCNFSM5JNHQ4EA&data=04%7C01%7Cweirc1%40live.lancs.ac.uk%7C846d1650df2c4428f41f08d9bb2b9022%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637746618037525216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=oxmeC%2BbHa%2FT4ToVbmYLLJy3VqB5BoDFwk%2FkjIxfURNE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cweirc1%40live.lancs.ac.uk%7C846d1650df2c4428f41f08d9bb2b9022%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637746618037525216%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=DIjAiSUHPeiin0dvOzCJl4FZpUOWtZSojkSBAMvu5Zo%3D&reserved=0> or Android<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cweirc1%40live.lancs.ac.uk%7C846d1650df2c4428f41f08d9bb2b9022%7C9c9bcd11977a4e9ca9a0bc734090164a%7C0%7C0%7C637746618037535170%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Xy4GTmDcxfu0wkVMoo2S%2F0tNb3B8RC5GT2nahMG5E7w%3D&reserved=0>.

**Comment by invariant** [comment]
Is it possible you are using an older version of the extension? The @ action was added in an update a couple of months ago.

**Comment by invariant** [comment]
Great! Auto-updating extensions is on the todo list :)
