### ISSUE TITLE
POPCLIP_BROWSER_URL and POPCLIP_BROWSER_TITLE don't work

### ISSUE THREAD

**Issue by solzard** [pilotmoon/PopClip-Extensions#1190]
Browser URL (`POPCLIP_BROWSER_URL`) and title (`POPCLIP_BROWSER_TITLE`) are not captured on my environment recently. 
Although I'm not perfectly confident this is the cause, they broke around May 23-24 after updating Brave Browser (Chromium) to the latest version. 
I confirmed they also don't work on a clean-installed latest Chrome.

Environments:
```
macOS 12.4
Brave Version 1.39.111 Chromium: 102.0.5005.61 (Official Build) (arm64)
Chrome Version 102.0.5005.61 (Official Build) (arm64)
```

**Comment by invariant** [comment]
Replied via https://forum.popclip.app/t/popclip-browser-url-and-popclip-browser-title-dont-work/908
