### ISSUE TITLE
install Join Lines extension error message.

### ISSUE THREAD

**Issue by jemerci** [pilotmoon/PopClip-Extensions#1191]
install Join Lines, repot error:
The path /var/folders/gf/8s36y8491txc9djblqwnbqp40000gn/T/TemporaryItems/(A Document Being Saved By PopClip)/JoinLines.popclipext does not contain a valid PopClip extension.

Reason: Could not load Config.plist. The XML may be malformed.

I have done:
1. download it from https://pilotmoon.com/popclip/extensions/page/JoinLines, same issue
2. donload it from github https://github.com/pilotmoon/PopClip-Extensions/blob/master/extensions/JoinLines.popclipextz, same issue.
3.  reboot the macOS catalina, same issue.
what can I do ???

**Comment by invariant** [comment]
Hi, what version of PopClip are you using? You will need to be running vesion 2022.5 or later.

**Comment by jemerci** [comment]
Hi Support,

THanks for your advice.
Popclip version: 201910(3032)
MacOS is Catalina 10.15.7 (19H1824)

When I update popclip , a error message as below:

"An error occurred while extracting the archive. Please try again later."

I have done:
1. try another 1 proxy to download the update, failed.
2. try another 2 proxy to download the update, update same failed.

sorry, what can I do?
