### ISSUE TITLE
Question: Is there a way to select text and then trigger a shortcut

### ISSUE THREAD

**Issue by StevenLi-DS** [pilotmoon/PopClip-Extensions#1200]
I'm trying to find an extension to trigger a shortcut after some texts are selected.

This could be useful when I need to select two lines of code and then run them in vscode (the run command is triggered by a shortcut)

https://user-images.githubusercontent.com/33796896/190938605-9720474f-750a-4e6e-ac7b-2821031b420e.mp4

**Comment by invariant** [comment]
There sure is, here is some more info on how to do it: https://forum.popclip.app/t/how-to-make-a-key-press-extension-in-popclip-textexpander-example/328/19

**Comment by StevenLi-DS** [comment]
@invariant Am I missing something here?
I get an `invalid key combo` error and tried the following two snippets.

```
# popclip
name: run code
key combo: return shift
```

```
# popclip
name: run code
key combo: shift
```

**Comment by invariant** [comment]
The modifiers have to be listed first so `shift return`.

Also a modifier on its own (`shift`) is invalid.

**Comment by StevenLi-DS** [comment]
@invariant Thanks you. That works! Btw, is there a way to set a whitelist for this extension so that I could customize different shortcuts for different apps? I only found a global blacklist in the settings.
![CS-X8adMv5A](https://user-images.githubusercontent.com/33796896/191350556-8c849e3d-6c10-4511-8e3e-ca85d118a7a0.png)

**Comment by invariant** [comment]
Yes you can use the required apps field in the extension configuration. Details are in the extensions documentation in this repository readme

**Comment by StevenLi-DS** [comment]
@invariant thank you!
