### ISSUE TITLE
PopClip slow down the 'select' action in Jetbrains IDE(Android Studio/Intelij IDEA)

### ISSUE THREAD

**Issue by NamekMaster** [pilotmoon/PopClip-Extensions#1201]
When selecting text in those IDE, and press `Ctrl+x` to cut text quickly, it cut twice actually. The first time cut the selected text, and the second time cut the whole line. If I select the text and wait until PopClip's popup appears then `Ctrl+x` is working properly. I also tried to keep only the built-in extension but it still happened. Everything would be ok if I quit PopClip. So, I guess this is PopClip's issue.

The reason why I said `slow down the select action` because of the `Ctrl+x` cuts whole line if there is no text selected.

Here is an example. The first time I waited until the popup appeared everything was ok, the second time cut twice.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/11484722/192675659-65f15973-1308-4165-928f-732cf5853951.gif)

**Comment by invariant** [comment]
Hello, yes, this is a known issue. I have been in contact with the jetbrains developers about it and they have investigated the matter, and they confirmed that the bug is within JetBrains code itself.

**Comment by invariant** [comment]
Actually, the issue we were looking at was a double paste issue rather than a double cut issue, but perhaps they are related.

**Comment by NamekMaster** [comment]
> 

You are right, there is also double paste.

**Comment by pilotmoon** [comment]
Closing as resolved in latest PopClip release (by excluding JetBrains IDE)
