### ISSUE TITLE
Instant Translate stopped working

### ISSUE THREAD

**Issue by misha-tgshv** [pilotmoon/PopClip-Extensions#1206]
The Instant Translate stopped working. The language selection window is constantly popping up and nothing happens further. Tell me, please, what could be the problem with?

![](https://d.pr/i/9HtTV9+.gif)

**Comment by invariant** [comment]
I confirm the fault and I am currentliy investigating.

**Comment by invariant** [comment]
It seems to be working again today. Can you confirm?

**Comment by misha-tgshv** [comment]
Thanks, everything works
