### ISSUE TITLE
Open in Arc Browser

### ISSUE THREAD

**Issue by jasonpott** [pilotmoon/PopClip-Extensions#1209]
Would it be possible to add the ARC browser to the openinbrowser extension for pop clip?

http://arc.net

**Comment by MohamedElashri** [comment]
It is easy, just add the following to [browsers.json](https://github.com/pilotmoon/PopClip-Extensions/blob/master/source/OpenInBrowser.popclipext/browsers.json) file in the extension. 

```
        {
            "name": "Arc",
            "bundleId": "company.thebrowser.Browser",
            "icon": "icons/fa6-brands-arc.svg",
            "link": "https://www.apple.com/safari/"
        },
```

And you should include `fa6-brands-arc.svg` logo file from their logo which is available [here](https://logotyp.us/logo/arc-browser/) for example

**Comment by pilotmoon** [comment]
Now done, available at: https://pilotmoon.com/popclip/extensions/page/OpenInBrowser
