### ISSUE TITLE
Notion extension cannot retrieve the URL and title of Arc browser

### ISSUE THREAD

**Issue by ajason** [pilotmoon/PopClip-Extensions#1215]
Notion extension cannot retrieve the URL and title of Arc browser

**Comment by pilotmoon** [comment]
PopClip does not yet have fully support for Arc browser. I hope to add this in next version (if Arc will support it).

**Comment by connor** [comment]
> PopClip does not yet have fully support for Arc browser. I hope to add this in next version (if Arc will support it).

Let me know if Arc isn’t supporting it and if not, what’s required. Thanks!

**Comment by masonfocus** [comment]
Want the same feature.

Arc is based on Chromium, seems not very hard to incorporate it, hopefully it will work out.

Thanks a bunch.

**Comment by pilotmoon** [comment]
@connor Thanks for commenting, sorry for the delay.

In Chrome/Sarari etc, PopClip uses a simple AppleScript command to retrieve browser URL/title.

For example: 

```applescript
tell application "Google Chrome"
  get URL of active tab of first window
end tell
```
Arc, however, does not implement this AppleScript API. If it did, PopClip could use it.

**Comment by connor** [comment]
@pilotmoon No problem.

[Here](https://browserinc.notion.site/Arc-AppleScript-API-897272210c784627ba3925a7610b02b6) is the documentation around our AppleScript APIs. You should be able to do:

```applescript
tell application "Arc"
	get the URL of active tab of front window
end tell
```

Let me know if you need anything else. Thanks!

**Comment by pilotmoon** [comment]
Awesome, thank you for the example and link. I hadn't realised Arc did already have an API for tabs.

**Comment by pilotmoon** [comment]
Arc page info support has now shipped as a beta feature in PopClip Build 4183: https://www.popclip.app/beta

**Comment by pilotmoon** [comment]
Hi @connor,

I wonder if you can advise on another scripting task for Arc.

I want to be able to open a url on Arc in a background tab, rather than as a new frontmost window.

Currentlt I can do this for Safari and mist Chromium-based browsers using a script like the following, but am having difficulty adapting it for Arc.
Can you suggest an approach?


```applescript
-- Safari versiopn -- opens in background tab by default
	tell front window of application id "com.apple.Safari"
		set newTab to make new tab with properties {URL: "https://example.com"}
	end tell
```

```applescript
-- Chrome version, need to explicitly switch back to original tab
	tell front window of application id "com.google.Chrome"
		set activeTabIndex to active tab index
		set newTab to make new tab with properties {URL:  "https://example.com"}
		if background then
			set active tab index to activeTabIndex
		end if
	end tell
```

**Comment by pilotmoon** [comment]
I can do something like

```
tell application "Arc"
		tell front window
			make new tab with properties {URL:"https://arc.net"}
			
			delay 5
			
			tell space 1
				make new tab with properties {URL:"https://thebrowser.company"}
			end tell
		end tell
	end tell
```
But this opens the tab as the foremost. Ideally, would be able to add a tab in the background (i.e. not focused)

**Comment by connor** [comment]
@pilotmoon Hey, thanks for bringing this up! Apologies about the delayed response. Confirming you've got everything you need?

**Comment by pilotmoon** [comment]
Yes, thanks @connor. I figured it out. Typing the question out to you got the old brain working enough to get me there. I appreciate the follow-up.
