### ISSUE TITLE
extension suggestion:Add support for the Warp terminal

### ISSUE THREAD

**Issue by macoswk** [pilotmoon/PopClip-Extensions#1219]
Run the selected text as a warp terminal command.
https://pilotmoon.com/popclip/extensions/page/RunCommand
warp
https://github.com/warpdotdev/Warp

**Comment by pilotmoon** [comment]
@macoswk Why do you keep makring this as completed? It is not completed.

**Comment by macoswk** [comment]
I've submitted an issue about the super right-click, and someone has already implemented it.
https://apps.apple.com/cn/app/%E8%B6%85%E7%BA%A7%E5%8F%B3%E9%94%AE-irightmouse/id1497428978?mt=12
<img width="606" alt="截屏2024-03-29 09 27 34" src="https://github.com/pilotmoon/PopClip-Extensions/assets/86730293/fa57f7f0-2ab6-41f9-af43-4b448d03e116">

**Comment by pilotmoon** [comment]
https://www.popclip.app/extensions/x/13U7m
