### ISSUE TITLE
url without % on it

### ISSUE THREAD

**Issue by mcnahum** [pilotmoon/PopClip-Extensions#1221]
Hello,
I'm trying to do an extension, the goal is to select an url ( https://mydomain.net/abcdef125) and to send it to an application.

All is working ok, except that when the application received the url it's:

https%3A%2F%2Fmydomain.net%2Fabcdef125

any idea how to fix it?

**Comment by pilotmoon** [comment]
It would help to see the actual extension source

**Comment by admMarcMi** [comment]
I simply did:

#popclip
name: Myapp
icon: circle filled 本
url: Myapp:{popclip text}

**Comment by mcnahum** [comment]
I simply did:

#popclip
name: Myapp
icon: circle filled 本
url: Myapp:{popclip text}

**Comment by pilotmoon** [comment]
Replied in forum: https://forum.popclip.app/t/url-without-on-it/1667
