### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by julzmon** [pilotmoon/PopClip-Extensions#1231]
Getting the following message when installing.
"No such executable in PATH: zsh"

**Comment by pilotmoon** [comment]
Which extension are you installing and what PopClip version are you using?

**Comment by julzmon** [comment]
Oh jeez sorry I didn't include it.

2023.9 (4226)
<img width="215" alt="image" src="https://github.com/pilotmoon/PopClip-Extensions/assets/46877/d2333592-6346-4a41-b1b3-9c3a431555a7">

Say
<img width="372" alt="image" src="https://github.com/pilotmoon/PopClip-Extensions/assets/46877/82b05f61-8078-4c16-a172-0dc33e9a43d2">

**Comment by 0xMH** [comment]
I'm having the same issue. MacOs version: 14.1.1 (23B81)

**Comment by pilotmoon** [comment]
Hi @julzmon , @0xMH — I shipped an update that may have addressed this with PopClip 2024.5. Can you confirm whether or not it solved the issue?

**Comment by julzmon** [comment]
Thanks I tested a few weeks back and was able to install. Thanks for the great work.
