### ISSUE TITLE
Pinyin Extension could not copy the results as before

### ISSUE THREAD

**Issue by yoghurtdewdew** [pilotmoon/PopClip-Extensions#1254]
I updated the Pinyin Extension some time ago as the newer version of popclip need new version of Extensions. But I found that before, the pinyin results could be copied after pinyin, but now it can't. Not being able to copy pinyin is very inconvenient for me. I really need to use Pinyin to take some notes, instead of typing pinyin characters manually, especially the tones are very difficult to type one by one. Please support auto copy Pinyin results!

**Comment by pilotmoon** [comment]
If you hold shift when you activate the extension, the result will be copied to the clipboard

**Comment by yoghurtdewdew** [comment]
> If you hold shift when you activate the extension, the result will be copied to the clipboard

Thank you very much! It could be able to copy pinyin now. That's great.
