### ISSUE TITLE
Add support for Kagi Translate

### ISSUE THREAD

**Issue by MachineOperator** [pilotmoon/PopClip-Extensions#1267]
There is a popclip plugin for Kagi already, which is cool: https://www.popclip.app/extensions/x/z9d8vd

Support for Kagi Translate would be great! You simply select text, click the "Kagi translate" button, and get some popup of unknown size showing the translation based on auto-detected language, plus maybe a drop down to correct the language if the detection made a mistake.

Text
- `https://translate.kagi.com/?text=<text>`

URL
- `https://translate.kagi.com/<url>`

**Comment by pilotmoon** [comment]
Great suggestion! Implemented in #c8fe3b54 but requires PopClip Beta.

Pre-release extension:
https://www.popclip.app/extensions/x/ezfkbp
