### ISSUE TITLE
Appigo Todo Pro

### ISSUE THREAD

**Issue by pilotmoon** [pilotmoon/PopClip-Extensions#159]
Ref: **[Conversation #421](https://secure.helpscout.net/conversation/4172051/421) / Gregg**

**Comment by invariant** [comment]
Ref: **[Conversation #3847](https://secure.helpscout.net/conversation/98929182/3847) / Home**

**Comment by invariant** [comment]
Ref: **[Conversation #4921](https://secure.helpscout.net/conversation/218815234/4921) / Amit**

**Comment by invariant** [comment]
Ref: **[Conversation #4971](https://secure.helpscout.net/conversation/225698511/4971) / Jassim**

**Comment by invariant** [comment]
Ref: **[Conversation #6395](https://secure.helpscout.net/conversation/517872134/6395) / Daniel**
