### ISSUE TITLE
Send to Scrivener

### ISSUE THREAD

**Issue by invariant** [pilotmoon/PopClip-Extensions#226]
Ref: **[Conversation #732](https://secure.helpscout.net/conversation/5051895/732) / Giovanni**

**Comment by invariant** [comment]
Ref: **[Conversation #3355](https://secure.helpscout.net/conversation/67088300/3355) / Markus**

**Comment by invariant** [comment]
Ref: **[Conversation #3694](https://secure.helpscout.net/conversation/86817498/3694) / Gregg**

**Comment by invariant** [comment]
Ref: **[Conversation #4763](https://secure.helpscout.net/conversation/193060929/4763) / John R.**

**Comment by invariant** [comment]
Ref: **[Conversation #5016](https://secure.helpscout.net/conversation/233760909/5016) / Robert**

**Comment by shenzo1** [comment]
Hey Nick, Is that something that will be developed some day? It would be such an awesome and simple workflow to be able to use popclip to clip stuff to Scrivener!
