### ISSUE TITLE
Mailplane

### ISSUE THREAD

**Issue by pilotmoon** [pilotmoon/PopClip-Extensions#4]
http://mailplaneapp.com/

**Comment by invariant** [comment]
Ref: **[Conversation #4367](https://secure.helpscout.net/conversation/152245219/4367) / Todtenbier**

**Comment by invariant** [comment]
Ref: **[Conversation #2829](https://secure.helpscout.net/conversation/42404923/2829) / Jens**

**Comment by invariant** [comment]
Ref: **[Conversation #4693](https://secure.helpscout.net/conversation/185588824/4693) / Edgar**
