### ISSUE TITLE
Terminal extension not launching terminal

### ISSUE THREAD

**Issue by invariant** [pilotmoon/PopClip-Extensions#522]
Ref: **[Conversation #2772](https://secure.helpscout.net/conversation/40739276/2772) / Roman**

**Comment by Joysr** [comment]
+1
10.9.5
the latest version.
not launching terminal, if iterm2 not installed. Asking for the location of iterm2.

**Comment by invariant** [comment]
If you are having this issue, can you try setting the terminal in the extension settings to iTerm2, press OK, then open the settings again and set it back to Terminal. Does it make a difference?

**Comment by russelgal** [comment]
runs both iterm2 and terminal.
and selected string inserted into the terminal. ( it's google translate:) )

**Comment by invariant** [comment]
Any AppleScript gurus who can figure out how [this script](https://github.com/pilotmoon/PopClip-Extensions/blob/master/source/RunCommand/RunTerminalCommand.applescript) is doing that?

**Comment by Joysr** [comment]
“setting the terminal in the extension settings to iTerm2, press OK, then open the settings again and set it back to Terminal”

Nothing changes.

Have tried deleting the iTerm2 part of the script and the Option in Config.plist, it doesn't work as well. The terminal part of the script works well in AppleScript App(changed {popclip text} to 'cd ~'), but won't work in the extension. Can't figure out why. :(

**Comment by invariant** [comment]
Ref: **[Conversation #3362](https://secure.helpscout.net/conversation/67486230/3362) / Philip**

**Comment by invariant** [comment]
To those having issues with th Terminal extension: I've just update the extension with a fix, which I think is working. Here: http://pilotmoon.com/popclip/extensions/page/Terminal
