### ISSUE TITLE
StrikeThrough

### ISSUE THREAD

**Issue by pilotmoon** [pilotmoon/PopClip-Extensions#57]
It would be great if you can add strikethrough to the basic formatting. This would be very very useful.

**Comment by invariant** [comment]
Ref: **[Conversation #3359](https://secure.helpscout.net/conversation/67356805/3359) / Alex**

**Comment by invariant** [comment]
Ref: **[Conversation #3490](https://secure.helpscout.net/conversation/75246550/3490) / Nathan**

**Comment by invariant** [comment]
Ref: **[Conversation #3490](https://secure.helpscout.net/conversation/75246550/3490) / Nathan**

**Comment by invariant** [comment]
Ref: **[Conversation #3661](https://secure.helpscout.net/conversation/84548056/3661) / Hamad's**

**Comment by invariant** [comment]
Ref: **[Conversation #3676](https://secure.helpscout.net/conversation/85305328/3676) / Raul**

**Comment by invariant** [comment]
Ref: **[Conversation #3772](https://secure.helpscout.net/conversation/93226032/3772) / Michael**

**Comment by syberknight** [comment]
agreed!

**Comment by invariant** [comment]
https://twitter.com/danmills7/status/709746973268512768

**Comment by syberknight** [comment]
thanks for the twitter link. 
yeah, i've noticed it's rather hard to get to the built-in strikethru (IMO).
if in the Notes app, for example, i have to...
1. highlight the text i want to strikeout
2. secondary-click on it
3. in the resulting popup menu, select the Font > Styles option
4. then click the "Favorite Styles" button
5. then click the dropdown menu that appears & select the StrikeThru option
6. then click the Apply button

the only way i've found to shorten that process up is to do that and then...
1. highlight that stricken through text
2. go to the Format menu & select the Font > Copy Style
3. now highlight other text i wanna strickout
4. then go back to the Format menu > Font > Paste Style
5. (of course, one would wanna use the keyboard shortcut for these to go even faster)

so i guess we're left to just providing feedback to Apple - right?
would there be any particular words/phrases to get right to the point for that or just explain how frustrating the above scenario is?

THANKS.

**Comment by invariant** [comment]
Ref: **[Conversation #5167](https://secure.helpscout.net/conversation/257503142/5167) / Aberdeenphoto**

**Comment by syberknight** [comment]
@invariant 
what are all these "Ref: Conversation #" links that just take you to a "help scout" page to sign up or sign in?
don't know what help scout is.

**Comment by invariant** [comment]
@syberknight  The help scout links are private to me, you aren't able to view them.

**Comment by invariant** [comment]
Ref: **[Conversation #3369](https://secure.helpscout.net/conversation/67665077/3369) / David**

**Comment by invariant** [comment]
Ref: **[Conversation #5625](https://secure.helpscout.net/conversation/331253886/5625) / 姜钰群**

**Comment by invariant** [comment]
Ref: **[Conversation #5626](https://secure.helpscout.net/conversation/331670771/5626) / Philip**

**Comment by invariant** [comment]
Ref: **[Conversation #6035](https://secure.helpscout.net/conversation/440316470/6035) / Bradley**

**Comment by invariant** [comment]
Ref: **[Conversation #6069](https://secure.helpscout.net/conversation/444978183/6069) / Jeffrey**

**Comment by invariant** [comment]
Ref: **[Conversation #6849](https://secure.helpscout.net/conversation/646666003/6849) / Greg**

**Comment by invariant** [comment]
Ref: **[Conversation #6898](https://secure.helpscout.net/conversation/666542406/6898) / Philip**

**Comment by syberknight** [comment]
wondering about the progress on this. several years later & now in to Mojave, is there any hope in getting strikethru added to the formatting options? thanks.

**Comment by invariant** [comment]
It’s technically very different to the other formatting options. Haven't figured out a way yet.

**Comment by jbaruch** [comment]
Any luck on this one?

**Comment by syberknight** [comment]
for what it's worth, as an alternative... i'm able to create a keyboard shortcut in System Prefs > Keyboard > Shortcut for some apps (like Pages & Notes) to give me a quick way to strikethrough text in those apps. for some reason in my test it doesn't work for "All Apps" but it does for at least these two apps individually. -2¢

**Comment by pilotmoon** [comment]
An update regarding Strikethough and PopClip:

https://forum.popclip.app/t/how-to-get-a-strikethrough-extension-in-popclip/2273

I'm going to close this now -- see the linked forum post fpr how to do Strikethrough in PopClip.
