### ISSUE TITLE
remove spaces

### ISSUE THREAD

**Issue by invariant** [pilotmoon/PopClip-Extensions#600]
Ref: **[Conversation #3131](https://secure.helpscout.net/conversation/53339702/3131) / Benoît**

**Comment by delook** [comment]
I have a prototype in use now. Do you have some more information on helpscout.net?

**Comment by invariant** [comment]
Ref: **[Conversation #5494](https://secure.helpscout.net/conversation/309394727/5494) / Jie**

**Comment by invariant** [comment]
Ref: **[Conversation #5539](https://secure.helpscout.net/conversation/317183108/5539) / Paco**

**Comment by invariant** [comment]
Ref: **[Conversation #6119](https://secure.helpscout.net/conversation/453552713/6119) / Jianwen**

**Comment by invariant** [comment]
Ref: **[Conversation #6221](https://secure.helpscout.net/conversation/475913769/6221) / Jparr.com**
