### ISSUE TITLE
Omnifocus 2 bug

### ISSUE THREAD

**Issue by invariant** [pilotmoon/PopClip-Extensions#602]
Ref: **[Conversation #3152](https://secure.helpscout.net/conversation/54604866/3152) / Mike**

**Comment by slyfogh** [comment]
I am not sure if this is the same problem but the current pop clip extension does not work with OmniFocus  2.0.4 (v87.19 r222363)

**Comment by invariant** [comment]
Closed this one as "can't fix". The extension only works in the Pro version of OmniFocus 2. (The standard version doesn't support AppleScript.)
