### ISSUE TITLE
Terminal extension does not work for me (Yosemite)

### ISSUE THREAD

**Issue by PandaWood** [pilotmoon/PopClip-Extensions#607]
Can I ask, what is supposed to happen when I choose the icon for the custom extension "Terminal" in PopClip?
After I install, select a valid command text, and hit popclip icon for Terminal, nothing happens -  absolutely nothing.
I tried iterm2 and the default, nothing.
I know the command was not run, so I was wondering whether it was attempted to run silently or is it supposed to launch a a terminal?

**Comment by invariant** [comment]
I've just update the Terminal extension with a fix. Can you re-download it and try again?

Here: http://pilotmoon.com/popclip/extensions/page/Terminal
