### ISSUE TITLE
Google Translate is not working

### ISSUE THREAD

**Issue by ManuDevelopia** [pilotmoon/PopClip-Extensions#661]
After selecting a text and selecting Google Translate icon, after spin stops no translation is shown, just an "x" to close.

**Comment by invariant** [comment]
Do you mean "Instant Translate" --- if so then please download the latest version from http://pilotmoon.com/popclip/extensions/page/InstantTranslate which should now work

**Comment by ManuDevelopia** [comment]
Thank you very much! I didnt come aware to check the repo.

**Comment by ManuDevelopia** [comment]
The issue can be closed, it´s working again, thanks and sorry for the inconveniences!
