### ISSUE TITLE
Day One extension is not working

### ISSUE THREAD

**Issue by invariant** [pilotmoon/PopClip-Extensions#686]
Ref: **[Conversation #3848](https://secure.helpscout.net/conversation/98994690/3848) / Edgar**

**Comment by chanoh** [comment]
The extension just opens Day One, but doesn't do anything else.

**Comment by invariant** [comment]
Ref: **[Conversation #5235](https://secure.helpscout.net/conversation/265765171/5235) / Richard**

**Comment by invariant** [comment]
Confirmed. Day One's "New Day One Entry With Selection" Services command is not workong (in Day One 2.1.1) hence the PopClip extension, which uses it, is failing.

**Comment by invariant** [comment]
Fixed in Feb 2016.

**Comment by invariant** [comment]
Reopened due to new problem Oct 2016. It seems "New Day One Entry With Selection" is not working. (Day One 2.1.1, Sierra.)

**Comment by invariant** [comment]
I have withdrawn the Day One extension from my site, and reported the bug to Day One.

**Comment by invariant** [comment]
Ref: **[Conversation #5321](https://secure.helpscout.net/conversation/279361287/5321) / Henry**

**Comment by invariant** [comment]
Fixed: http://pilotmoon.com/popclip/extensions/page/DayOne
