### ISSUE TITLE
Rdio

### ISSUE THREAD

**Issue by pilotmoon** [pilotmoon/PopClip-Extensions#70]
https://twitter.com/richardmhowell/status/279714131412647937

**Comment by invariant** [comment]
Ref: **[Conversation #2932](https://secure.helpscout.net/conversation/45927205/2932) / Konstantin**

**Comment by invariant** [comment]
Ref: **[Conversation #5999](https://secure.helpscout.net/conversation/430809901/5999) / Qin**
