### ISSUE TITLE
run command plugin could not call iTerm 

### ISSUE THREAD

**Issue by bao3** [pilotmoon/PopClip-Extensions#752]
run command plugin just could run with terminal app , could not call iTerm ... plz fix it , Thx

**Comment by alxstu** [comment]
hi @bao3, try this: https://github.com/alxstu/iTerm2Nightly-popclip-extension 
runs with iterm2 nightly builds and the actual iterm2 beta.

**Comment by bao3** [comment]
it did work ~ thanks , this issue should be closed .

**Comment by invariant** [comment]
Now updated main Terminal extension with term2 v2.9+ support.
