### ISSUE TITLE
Is it possible to fix 'New Note' bug in the 'Notes' extension

### ISSUE THREAD

**Issue by nikitavoloboev** [pilotmoon/PopClip-Extensions#765]
When you highlight some text and a note gets added, aside from the note, every single note has ‘New Note’ on top of each of the new entries. like so : 

![3c07010f-5b83-4f6e-b1f5-ea070eb64f88](https://cloud.githubusercontent.com/assets/6391776/14266223/0c01c132-fac7-11e5-9b5a-5e44e4b00cd3.png)

Here I just added the word ‘test’ to add. You can try it for yourself to see. 

Thank you and I hope this can be fixed.

**Comment by invariant** [comment]
Fixed in latest version of notes (now uses system Notes share panel): https://pilotmoon.com/popclip/extensions/page/Notes
