### ISSUE TITLE
Is it possible to make it so that when you add notes with 'Notes' extension, 'Notes' window does not come to the front

### ISSUE THREAD

**Issue by nikitavoloboev** [pilotmoon/PopClip-Extensions#766]
For example I add the highlighted text to the notes app and the text gets sent to the notes app silently. 

It is really annoying to have Notes application pop up every time I add some string of text.

**Comment by invariant** [comment]
Latest version of notes now uses system Notes share panel; notes app does not pop uo any more.

https://pilotmoon.com/popclip/extensions/page/Notes
