### ISSUE TITLE
Cannot Add: Malformed XML

### ISSUE THREAD

**Issue by calebaharrison** [pilotmoon/PopClip-Extensions#783]
Hi,

I keep getting notified that my extension cannot be added because the Config.plist cannot load.

![](https://cloud.githubusercontent.com/assets/5065084/15756172/13e2f51c-28ce-11e6-8593-5d98a69ccf5c.png)

I verified that the official "Alfred" extension would load, then copied and pasted the Config file into a folder with my icon and applescript file. I then changed the respective elements of the Config file to apply to my extension.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>Actions</key>
	<array>
		<dict>
			<key>AppleScript File</key>
			<string>omniAdd.applescript</string>
			<key>Image File</key>
			<string>omniAdd.png</string>
			<key>Regular Expression</key>
			<string>(?s)^[^\n\r]{1,300}$</string>
			<key>Title</key>
			<string>OmniAdd</string>
		</dict>
	</array>
	<key>Apps</key>
	<array>
		<dict>
			<key>Bundle Identifier</key>
			<string>com.omnigroup.OmniFocus2</string>
			<key>Check Installed</key>
			<true/>
			<key>Link</key>
			<string>http://www.omnigroup.com/OmniFocus2</string>
			<key>Name</key>
			<string>OmniFocus 2</string>
		</dict>
	</array>
	<key>Extension Description</key>
	<string>Send highlighted text to Omnifocus Bibliography project.</string>
	<key>Extension Identifier</key>
	<string>com.calebaharrison.OmniAdd</string>
	<key>Extension Name</key>
	<string>OmniAdd</string>
</dict>
</plist>
```

I combine my `Config.plist`, `omniAdd.png`, and `omniAdd.applescript` files into a folder, zip that folder, and then change the extension from '.zip' to '.popclipext'. Then I get the error when I double-click the extension.

**Comment by invariant** [comment]
Your XML looks fine. If you send me a zip of the exact extension you are trying to load I can take a look.

**Comment by calebaharrison** [comment]
Zip added - thanks!

[omniAdd.zip](https://github.com/pilotmoon/PopClip-Extensions/files/298911/omniAdd.zip)

**Comment by invariant** [comment]
It's loading OK for me - no XML error.

**Comment by calebaharrison** [comment]
Weird. Should I uninstall/reinstall PopClip?

**Comment by invariant** [comment]
Maybe worth a try ... or try rebooting. Could be come kind of file system caching issue maybe. (?)

**Comment by calebaharrison** [comment]
Rebooted, deleted and installed - still won't work! Other new extensions work, though..

**Comment by invariant** [comment]
Sure you've sent me the *exact* files that aren't working?

**Comment by invariant** [comment]
Does this work? [omniAdd.popclipext.zip](https://github.com/pilotmoon/PopClip-Extensions/files/298924/omniAdd.popclipext.zip)

**Comment by calebaharrison** [comment]
Yes! It did. Okay. There's a good chance this was just me being stupid. Which of the following is the correct process:

### A
1. Create files
2. zip files together
3. change extension from .zip to .popclipext
4. open file.popclipext

or

### B
1. Create files
2. zip files together
3. change extension from .zip to .popclipext
4. zip file.popclipext

One additional bit of info: when I tried renaming the file to omniAdd.popclipextz (with a 'z'), I received an error that there already exists a file named 'omniAdd' with the extension 'popclipextz'. Which, as far as I could tell, was false..

**Comment by calebaharrison** [comment]
(Also - thank you!!)

**Comment by invariant** [comment]
Neither, it is:
1. Create files
2. Enclose in folder with extension .popclipext (no z)

Then (optionally, for distribution)
3. Zip the folder
4. Rename zip file to .popclipextz (with a z)

**Comment by ottersoftware** [comment]
I've just had the same issue and a reboot fixed it for me.
