### ISSUE TITLE
ShortenLink not Functioning

### ISSUE THREAD

**Issue by shabob** [pilotmoon/PopClip-Extensions#784]
the ShortenLink extension is currently non-functional.

this is almost certainly to do with the move of is.gd and v.gd to https, per
[the developer site](https://is.gd/news.php)

looking at the source, apart from the change of the api address to the https://is.gd, i *think* this would require a rewrite of the python script to use urllib2's httpshandler

**Comment by invariant** [comment]
Thanks for the info, I was just about to start investigating this and looks you have saved me some time.

**Comment by invariant** [comment]
Fixed now. All users will need to re-download from https://pilotmoon.com/popclip/extensions/page/ShortenLink
