### ISSUE TITLE
Todoist - problem signing in

### ISSUE THREAD

**Issue by invariant** [pilotmoon/PopClip-Extensions#794]

**Comment by invariant** [comment]
DMs

**Comment by invariant** [comment]
Ref: **[Conversation #4980](https://secure.helpscout.net/conversation/227335259/4980) / Cory**

**Comment by jdaverth** [comment]
Ditto here -- any movement on a fix?  I cannot access the conversation link above.

**Comment by invariant** [comment]
Ref: **[Conversation #5069](https://secure.helpscout.net/conversation/242669400/5069) / Yaphet**

**Comment by invariant** [comment]
Ref: **[Conversation #5070](https://secure.helpscout.net/conversation/242764295/5070) / Romain**

**Comment by invariant** [comment]
Fixed https://pilotmoon.com/popclip/extensions/page/Todoist
