### ISSUE TITLE
Tembo

### ISSUE THREAD

**Issue by pilotmoon** [pilotmoon/PopClip-Extensions#84]
https://twitter.com/kantorde/status/288299550421180416

**Comment by invariant** [comment]
Ref: **[Conversation #4099](https://secure.helpscout.net/conversation/121115836/4099) / 黄**

**Comment by invariant** [comment]
Ref: **[Conversation #4394](https://secure.helpscout.net/conversation/155083652/4394) / Frank**

**Comment by invariant** [comment]
Ref: **[Conversation #4147](https://secure.helpscout.net/conversation/127611087/4147) / Ubaldo Andrea**

**Comment by invariant** [comment]
Ref: **[Conversation #4110](https://secure.helpscout.net/conversation/122011529/4110) / Michele**

**Comment by invariant** [comment]
Ref: **[Conversation #3316](https://secure.helpscout.net/conversation/64791367/3316) / Chris**

**Comment by invariant** [comment]
Ref: **[Conversation #5785](https://secure.helpscout.net/conversation/368180221/5785) / Matt**
