### ISSUE TITLE
Goodreads search

### ISSUE THREAD

**Issue by invariant** [pilotmoon/PopClip-Extensions#877]
Ref: **[Conversation #2832](https://secure.helpscout.net/conversation/42515220/2832) / Vlad**

**Comment by auxbuss** [comment]
FYI, I have created an [extension to search Goodreads](https://gitlab.com/auxbuss/popclip-goodreads)

**Comment by invariant** [comment]
Ref: **[Conversation #6322](https://secure.helpscout.net/conversation/498945303/6322) / Kenneth**

**Comment by tillchen** [comment]
@auxbuss Thx! Saved me a lot of time!

**Comment by invariant** [comment]
Done: https://pilotmoon.com/popclip/extensions/page/Goodreads

**Comment by auxbuss** [comment]
This extension has disappeared from the list of extensions: https://pilotmoon.com/popclip/extensions/

The download link still works, but the page it's on no longer refers to it.
